name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install wget curl gcc clang cmake git build-essential libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev -y

    - name: Download & Build raylib
      run: git clone https://github.com/raysan5/raylib.git raylib && cd raylib/src/ && make PLATFORM=PLATFORM_DESKTOP

    - name: Install raylib to runner
      run: cd raylib/src/ && sudo make install
    
    - name: Build game
      run: make

    - name: Clean
      run: make clean

      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        # Artifact name
        name: Build (Linux x86_64)
        
        path: ./game

    
  build-win:

      runs-on: windows-latest
  
      steps:
      - uses: actions/checkout@v3
  
      - name: Install git on windows
        # You may pin to the exact commit or the version.
        # uses: crazy-max/ghaction-chocolatey@0e015857dd851f84fcb7fb53380eb5c4c8202333
        uses: crazy-max/ghaction-chocolatey@v3.0.0
        with:
          # Arguments to pass to Chocolatey
          args: install git

      - name: Install Dependencies
        run: git clone https://github.com/Microsoft/vcpkg.git && .\vcpkg\bootstrap-vcpkg.bat && vcpkg install raylib:x64-windows && vcpkg integrate install && vcpkg install raylib
      
      - name: Download & Build raylib
        run: git clone https://github.com/raysan5/raylib.git raylib && cd raylib/src/ && make PLATFORM=PLATFORM_DESKTOP
  
      - name: Install raylib to runner
        run: cd raylib/src/ && sudo make install
      
      - name: Build game
        run: make
  
      - name: Clean
        run: make clean
  
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name
          name: Build (Windows x64)
          
          path: game.exe
