name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install wget curl gcc clang cmake git build-essential libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev -y
    
    - name: Get raylib
      run: wget https://github.com/raysan5/raylib/archive/refs/tags/4.2.0.tar.gz

    - name: Extract raylib
      run: tar xzf 4.2.0.tar.gz

    - name: Rename raylib folder
      run: mv raylib-4.2.0 raylib
    
    - name: Build game
      run: make

    - name: Clean
      run: make clean
