name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install wget curl gcc clang cmake git build-essential libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev -y

    - name: Download & Build raylib
      run: git clone https://github.com/raysan5/raylib.git raylib && cd raylib/src/ && make PLATFORM=PLATFORM_DESKTOP

    - name: Install raylib to runner
      run: sudo make install
    
    - name: Build game
      run: make

    - name: Clean
      run: make clean
